columnSuffix: null
contentColumnType: string
fieldGroup: 0e18f0fc-7dbd-4a1e-b8f8-07cbf293100b # Site Identity
handle: favicon
instructions: null
name: favicon
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:25a453ed-97ea-4480-921e-0c572facc9d3' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:25a453ed-97ea-4480-921e-0c572facc9d3' # Uploads
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
