dateModified: 1660667338
elementSources:
  verbb\comments\elements\Comment:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - comment
        - commentDate
        - ownerId
        - voteCount
        - flagCount
        - upvote_voteTally
        - upvote_totalVotes
        - upvote_totalUpvotes
        - upvote_totalDownvotes
      type: native
email:
  fromEmail: no-reply@route-404.be
  fromName: spelendatabase
  replyToEmail: no-reply@route-404.be
  template: ''
  transportSettings:
    apiKey: Tg70g9E45IDLB9vxMStnaw
    subaccount: ''
    template: ''
  transportType: perfectwebteam\mailchimptransactional\mail\MailchimpTransactionalAdapter
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a238770-7d8c-4794-a727-2c66c79169ea: 'link naar pagina' # link naar pagina
    0ae3328f-cf7d-475c-afbe-b3254f0112ea: Register # Register
    0e18f0fc-7dbd-4a1e-b8f8-07cbf293100b: 'Site Identity' # Site Identity
    1cc25933-d89f-446d-a114-b66154169e66: 'Materiaal lijst' # Materiaal lijst
    1d8f21b2-d097-4a76-a1c3-b597e1862651: 'Navigatie item' # Navigatie item
    1de13740-5647-4176-91d5-bc306aca20ad: About # About
    1fafad87-02cb-4572-8313-1ce585e2bf05: 'Aantal groepen' # Aantal groepen
    2c5e6922-a62e-4f6e-8354-083e79393c83: 'Spel toevoegen' # Spel toevoegen
    2c92f68d-b6fc-409a-911d-cf4ab4142049: testMatrixBlock # testMatrixBlock
    2c509aa5-68ac-4202-8632-8340a7516dd9: 'Gewone gebruiker' # Gewone gebruiker
    02da3bc8-268a-4e70-8522-92ffa53b4ecf: 'Nav Item' # Nav Item
    2f9215d4-56e5-440b-a99f-d505f732a5fb: link # link
    3cb2bd46-d530-4171-ac8a-071b0492c1ac: 'Ondersteuning om zelf een spel te maken' # Ondersteuning om zelf een spel te maken
    3ecd3071-dffb-4c9a-9434-7f247d325058: 'Spel toevoegen' # Spel toevoegen
    4a023bf0-7e4d-47d0-b47d-331526fb0d33: fze # fze
    05c3f2cb-70ce-45fd-adde-74f4be96cf0f: redactor # redactor
    5c7ffd2c-f680-4e53-ae10-eab3a0435bf4: 'Maximum aantal spelers' # Maximum aantal spelers
    5c29cdee-b532-4da6-94de-fc4b3ef39467: Terrein # Terrein
    5dccd971-e9cf-4888-8f8b-b6518e7621dc: 'is publiek' # is publiek
    5f94dadc-3d09-41d0-812d-ebde9b91d3a8: Blog # Blog
    6a1c89a2-84a5-4ec6-825a-eee41066ca29: Homepage # Homepage
    6ca202fc-2d48-46c9-a5a6-487cfa009237: 'Spelen zoeken'
    6d1b6141-70c2-4c2a-841b-a036eeb10aae: 'Link naar pagina' # Link naar pagina
    6dfee47b-10a4-4592-bbb5-37c9f1d6d89f: 'Ondersteuning om zelf een spel te maken' # Ondersteuning om zelf een spel te maken
    6e6da057-c74a-4bb3-9626-52fa6603ebf1: Favorites # Favorites
    6ead53d7-0002-4a4a-af83-1c0b3dce0c19: Login # Login
    6eda61ff-3cee-4630-a673-98b001b9b748: Blog # Blog
    6f7fb0b4-c460-4f71-a9d6-80d4dfa91ef5: 'Eén tegen allen opdrachten' # Eén tegen allen opdrachten
    6f7119f2-4379-47e0-ba06-f43685d65fff: 'Materiaal item' # Materiaal item
    8a13966e-c6f9-4bc1-b242-db834badd512: 'Maximum leeftijd' # Maximum leeftijd
    8cb30964-de8f-4299-9a2b-7e8cfbe03360: Homepage # Homepage
    08d1e13d-6103-45e5-8908-49b8c1280505: 'Profiel bewerken' # Profiel bewerken
    8d3c63d4-dcaf-494b-b873-229679852123: 'Mijn knutselopdrachten' # Mijn knutselopdrachten
    8fee1281-9138-49c3-8b8e-5343244c2be3: Common # Common
    9e4a4d57-8218-48f5-95a2-350a4b150ddc: 'Mijn knutselopdrachten' # Mijn knutselopdrachten
    9f4915ff-f144-41f9-b90e-4d517b0950bd: Homepage # Homepage
    11b6b233-12c3-4b4f-8b21-7db92eb95807: 'Mijn Profiel' # Mijn Profiel
    21efaced-8678-4323-a87b-a1054772fab0: Link # Link
    25a453ed-97ea-4480-921e-0c572facc9d3: Uploads # Uploads
    27b33b16-da29-4cd2-a97b-39557f2c0e23: Standaard # Standaard
    28ce2114-46d8-4431-a66b-5864db7ab615: 'Spel type' # Spel type
    0033ad93-75b0-46bf-af03-b5686b901bf8: 'Spelen Navigatie' # Spelen Navigatie
    33edeee0-e5bd-47bb-a308-f995fd7baec7: url # url
    38a829e3-b181-49ee-baa2-561b893a6e0a: 'Spel materiaal' # Spel materiaal
    46d1f524-1888-4252-966d-d33a9d20d89f: Standaard # Standaard
    55b9367d-1681-42a2-9c38-e9019269f699: 'Dodemomentspelletje toevoegen' # Dodemomentspelletje toevoegen
    71f4e72f-939f-48c3-ade8-a9186988278c: 'Public Schema' # Public Schema
    83a6d2e6-f1e0-4916-abc8-a37707d95954: 'Mijn spelen' # Mijn spelen
    89aeda29-7de1-4a24-b237-7ca544556d1a: Speluitleg # Speluitleg
    95dd9080-1a19-4454-a0b5-7052e0d5e882: 'Overzicht dodemomentspelletjes' # Overzicht dodemomentspelletjes
    146d3948-abce-4b2f-b9f9-cdf5f7e99597: Bestanden # Bestanden
    167e8d09-1193-4c1b-88a3-1b072e697bea: 'Minimum leeftijd' # Minimum leeftijd
    228a6b11-5f90-4b0f-bd62-355a81cefe39: favicon # favicon
    259ec406-30de-46aa-9797-029f8d0f20d2: 'Maximum aantal spelers' # Maximum aantal spelers
    322bf92a-0dd8-4b01-bdc9-3bb080072db8: 'Overzicht één tegen allen opdrachten' # Overzicht één tegen allen opdrachten
    332ee3b0-a4d0-4cc4-9d9f-d467ef67b06d: 'Overzicht dodemomentspelletjes' # Overzicht dodemomentspelletjes
    585cf87e-4f27-48b3-a715-17420e6f5be5: Navigatie # Navigatie
    603f99df-a8db-4297-bbf4-346789d995a3: 'Willekeurig spel' # Willekeurig spel
    691e3054-1e3e-401f-a831-43f2f43e969d: 'Spel type' # Spel type
    940a4856-c438-4dc9-ba20-96043efe8c78: 'Doel van het spel' # Doel van het spel
    6812e2a8-90da-4343-a3d0-a7ecdded2a20: Wishlist # Wishlist
    06865b08-0e90-49f8-a9fc-67040777d7e1: Naam # Naam
    7508f146-500b-454c-b8a0-12390b0089dd: 'spel nav' # spel nav
    7813ec25-2f74-44af-b2d4-87056478950a: fze # fze
    8086b01c-8350-4557-8e6e-60255bcc0337: 'matrix Name' # matrix Name
    926861b1-5ccd-4b3d-985b-614aa962bc5d: Knutselopdrachten # Knutselopdrachten
    949190a5-0720-4d54-af48-03207ae923c2: Standaard # Standaard
    4837907b-689e-4038-9f17-b6d6c15e8479: Navigatie # Navigatie
    5402668f-57a2-4d2d-a55b-15760b93340f: 'Minimum aantal spelers' # Minimum aantal spelers
    91772575-2882-41d6-95d7-d5a54d46fb06: 'Thema type' # Thema type
    a9d03940-ad33-4c4f-8773-a1eb25928afb: 'Overzicht spelen' # Overzicht spelen
    a196e0e6-3f10-4c9b-857f-27ac17884afa: spelendatabase # spelendatabase
    a621ad91-c112-4a5d-aed1-9ebfb7b1fab6: 'Overzicht knutselopdrachten' # Overzicht knutselopdrachten
    a31540ae-f9f2-4f76-b6a2-f8b11080b4cb: Standaard # Standaard
    adde1b0a-fe7f-4b28-8628-ae62f6ad5a5d: 'Knutselopdracht toevoegen' # Knutselopdracht toevoegen
    b03c1c4f-f1f5-4de2-8cf3-55dc35f283aa: 'Mijn dodemomentspelletje' # Mijn dodemomentspelletje
    b037657d-9197-46c5-8666-b2c35c5c4b88: 'Uitgelichte blogpost' # Uitgelichte blogpost
    b3b5d1d5-4a61-44db-b610-8f74faf95f51: 'Overzicht spelen' # Overzicht spelen
    b9c67985-d40e-4cbd-996d-9b6f511a9f48: Blogberichten # Blogberichten
    b654d6b4-8939-4ca1-a408-5c7f05f7d94e: 'Dodemomentspelletje toevoegen' # Dodemomentspelletje toevoegen
    b92690fb-549e-494d-8c1b-1481340be882: 'Wachtwoord Reset' # Wachtwoord Reset
    bb4dab03-1b87-4c75-b141-84eee5b64c8b: 'Dode moment spelletjes' # Dode moment spelletjes
    c9c4c4e4-1594-49b6-86fc-377c72c8303a: spelendatabase # spelendatabase
    c16c586b-d1cf-4d7d-b9e7-b3d915e296e1: Speelduur # Speelduur
    c86d9b88-9b29-4d8f-a5ef-0e3c3a2578eb: 'Spelen zoeken'
    c7895103-1c1c-4d23-920a-a99413e20b96: Standaard # Standaard
    caa64a59-e2d6-41ee-b915-08d1fb922d15: 'item Naam' # item Naam
    cb0443b6-2e43-4d70-b39c-1e9ab6876455: 'Overzicht één tegen allen opdrachten' # Overzicht één tegen allen opdrachten
    cb5fd577-a260-423e-8777-dc3e59af997d: Intro # Intro
    cbd07e0a-3383-4035-924b-222116f901cb: 'Willekeurig spel' # Willekeurig spel
    d084937e-0169-46e2-9fc8-996e457cdb13: 'Matrix Amount' # Matrix Amount
    d18c16ef-3965-4d12-9400-4db1d4c697e4: 'benaming materiaal' # benaming materiaal
    d92743f8-2eb6-4650-8b71-f7cf353ed16e: 'Profiel bewerken' # Profiel bewerken
    d94396ce-5586-4fae-adcc-084f65e8ed20: Intensiteit # Intensiteit
    db756868-c5be-4387-a9ca-36e74e7cfd2c: Login # Login
    df1ed38c-1bc0-4b4f-a618-65b32ef2dbff: 'Overzicht knutselopdrachten' # Overzicht knutselopdrachten
    df4ee256-846a-416c-9e10-243b726f0e71: 'Minimum aantal spelers' # Minimum aantal spelers
    e2a75ff5-e879-43b9-900a-162b0240017c: SiteIdentity # SiteIdentity
    e5c64ea9-1ade-4016-a8b7-9bab6c10d632: Register # Register
    e7bf288e-7066-4622-9d28-96ee8a3a6a59: About # About
    e19a312d-2048-4cb2-b6d6-559faf353306: 'Hero Image' # Hero Image
    e586182b-8c3f-4827-8a5a-bb87df1c18cd: naam # naam
    ea893c32-648c-4ad1-877a-0146c7cd8552: 'Mijn spelen' # Mijn spelen
    ec954f96-2299-4b7d-9fbb-97c974832a96: Title # Title
    f014de6c-fdcb-4f4b-a023-354dbb6a4e5e: 'Wachtwoord Reset' # Wachtwoord Reset
    f2b91cbe-dc96-4130-a71f-326e99ec6d1e: testMatrix # testMatrix
    f3d4eff4-1789-4617-a4c9-e5bbc6d1bbcd: 'Knutselopdracht toevoegen' # Knutselopdracht toevoegen
    f5e119ac-c04b-4593-aeef-f2a70dad5a26: Thema # Thema
    f8b402c2-1415-4442-ad43-66490a00ab05: 'Terrein type' # Terrein type
    f19d176f-7128-401e-8b26-011cd7aad5f7: 'Mijn dodemomentspelletje' # Mijn dodemomentspelletje
    f2589fc5-09a5-4bc1-8d53-b6688f239a39: Spelen # Spelen
    f9172996-eb36-48fb-84f8-4f35c3728c65: 'hoeveelheid materiaal' # hoeveelheid materiaal
    fbc67a4a-697c-4b64-bf27-60d2e76ca405: Spel # Spel
    ff82736d-00fb-4275-abeb-a6f5a2fe19ae: 'Mijn Profiel' # Mijn Profiel
plugins:
  comments:
    edition: standard
    enabled: true
    licenseKey: XA1KJPDO0IOJS7YDU09I7XAF
    schemaVersion: 1.1.7
    settings:
      allowFlagging: true
      allowGuest: false
      allowGuestFlagging: false
      allowGuestVoting: false
      allowVoting: true
      autoCloseDays: null
      closed: false
      defaultQueryStatus:
        - approved
      downvoteCommentLimit: 5
      enableGravatar: false
      enableSpamChecks: true
      flaggedCommentLimit: 5
      guestNotice: null
      guestRequireEmailName: true
      guestShowEmailName: true
      hideVotingForThreshold: false
      indexSidebarGroup: true
      indexSidebarIndividualElements: false
      indexSidebarLimit: 25
      maxReplyDepth: '2'
      maxUserComments: null
      moderatorUserGroup: null
      notificationAdminEnabled: false
      notificationAuthorEnabled: true
      notificationFlaggedEnabled: false
      notificationModeratorApprovedEnabled: false
      notificationModeratorEnabled: false
      notificationReplyEnabled: true
      notificationSubscribeAuto: false
      notificationSubscribeCommentEnabled: false
      notificationSubscribeDefault: true
      notificationSubscribeEnabled: false
      outputDefaultCss: true
      outputDefaultJs: true
      permissions:
        __assoc__:
          -
            - craft\elements\Asset
            - '*'
          -
            - craft\elements\Category
            - '*'
          -
            - craft\elements\Entry
            - '*'
          -
            - craft\elements\User
            - '*'
      placeholderAvatar: null
      recaptchaEnabled: false
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      requireModeration: false
      securityBanned: null
      securityFlooding: null
      securityMatchExact: false
      securityMaxLength: null
      securityModeration: null
      securitySpamlist: null
      showAvatar: true
      showCustomFieldInstructions: false
      showCustomFieldNames: false
      showTimeAgo: true
      sortDefaultDirection: asc
      sortDefaultKey: structure
      structureUid: 988ad244-63b3-42cb-8d61-9ecb64ef82ff
      templateEmail: null
      templateFolderOverride: null
      useQueueForNotifications: false
  enupal-socializer:
    edition: standard
    enabled: true
    licenseKey: RGSV7GOMT70LGMR8AX5JRWQH
    schemaVersion: 2.0.0
    settings:
      enableCp: 1
      enableFieldMapping: '1'
      enableFieldMappingPerProvider: ''
      enableUserSignUp: '1'
      fieldMapping:
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
        -
          __assoc__:
            -
              - targetUserField
              - ''
      userGroupId: '1'
  mailchimp-transactional:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  upvote:
    edition: standard
    enabled: true
    licenseKey: 6HO10Z275HYB0LTU6THCE7XC
    schemaVersion: 2.0.0
    settings:
      allowDownvoting: true
      allowFontAwesome: true
      allowVoteRemoval: true
      keepVoteLog: false
      preload: true
      requireLogin: true
  wishlist:
    edition: standard
    enabled: true
    licenseKey: PN7LQEN1FURWX0CI5YFY1D9Q
    schemaVersion: 1.0.4
    settings:
      allowDuplicates: false
      cookieExpiry: 0
      manageDisabledLists: true
      mergeLastListOnLogin: true
      pdfAllowRemoteImages: true
      pdfFilenameFormat: 'Wishlist-{id}'
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pdfPath: _pdf/wishlist
      pluginName: Wishlist
      purgeEmptyGuestListsOnly: true
      purgeEmptyListsOnly: true
      purgeInactiveGuestListsDuration: P1D
      purgeInactiveLists: true
      purgeInactiveListsDuration: P3M
      showListInfoTab: true
      updateItemSearchIndexes: true
      updateListSearchIndexes: true
system:
  edition: pro
  live: true
  name: spelendatabase
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: Europe/Brussels
